### ISSUE TITLE
Disable "STARTTLS"?

### ISSUE THREAD

**Issue by yacinelazaar** [bitnami/bitnami-docker-discourse#108]
Hi,

Im currently running Discourse on a docker setup. The issue is the smtp config: it's currently configured with Mailgun using the env vars mentionned in the docs:

      - SMTP_HOST=smtp.mailgun.org
      - SMTP_USER=${SMTP_NAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=465

Emails are not sent while using the port 465. Using 587 though works fine.
Inside the container, the config file has the variable `smtp_enable_start_tls` set to `true`. Is there a way to change it to `false` and use other ports than 587?

**Comment by juan131** [comment]
Hi @yacinelazaar 


Did you try to set the env. variable * SMTP_TLS** to **"false"**? Check more information in this section of the README.md: https://github.com/bitnami/bitnami-docker-discourse#smtp-configuration

**Comment by yacinelazaar** [comment]
Hey @juan131 

I already tried that (and just did a double check). 
With `SMTP_TLS=false`, The configuration under /opt/bitnami/discourse/config/discourse.conf still shows  `smtp_enable_start_tls = true`.
`smtp_enable_start_tls` is also present as an env var inside the container and I couldn't override it.

**Comment by yacinelazaar** [comment]
using 'bitnami/discourse:2'.
Will use a newer image and let you know.

**Comment by yacinelazaar** [comment]
@juan131 same thing with 'bitnami/discourse:2.3.2'

**Comment by juan131** [comment]
Hi @yacinelazaar 

I found the issue and I'm working on a simple fix. I'll come back to you once we released a new image addressing the issue. Thanks so much for reporting it.

JFYI the `bitnami/discourse:2` is a rolling tag and it points to the latest version of the image in the `2` branch. Learn more about the tags used on Bitnami images in the link below:

https://github.com/bitnami/bitnami-docker-discourse#supported-tags-and-respective-dockerfile-links

**Comment by juan131** [comment]
Hi @yacinelazaar 

We just released a new revision of the image (**2.3.2-40**) which accepts `yes/no` instead of `true/false` as valid values for the env. variable **SMTP_TLS**.

I tested using this [docker-compose.yaml](https://github.com/bitnami/bitnami-docker-discourse/blob/master/docker-compose.yml) with the changes below:

```diff
   discourse:
-    image: 'bitnami/discourse:2'
+    image: 'bitnami/discourse:2.3.2-r40'
     ports:
       - '80:3000'
     depends_on:
...
       - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
       - DISCOURSE_HOSTNAME=www.example.com
   sidekiq:
-    image: 'bitnami/discourse:2'
+    image: 'bitnami/discourse:2.3.2-r40'
     depends_on:
       - discourse
     volumes:
...
       - DISCOURSE_HOST=discourse
       - DISCOURSE_PORT=3000
       - DISCOURSE_HOSTNAME=www.example.com
+      - SMTP_HOST=smtp.gmail.com
+      - SMTP_PORT=587
+      - SMTP_USER=your_email@gmail.com
+      - SMTP_PASSWORD=your_password
+      - SMTP_TLS=no
 volumes:
   postgresql_data:
     driver: local
```

```console
$ docker-compose up -d
$ docker-compose exec sidekiq cat /opt/bitnami/discourse-sidekiq/conf/discourse.conf
...
smtp_user_name = your_email@gmail.com
smtp_password =  your_password
smtp_enable_start_tls = false
smtp_authentication = login
```

**Comment by yacinelazaar** [comment]
@juan131 Indeed that value is now properly affected but sadly it does not solve the issue.
Port 465 is not blocked and i could run `telnet smtp.mailgun.org 465` within both containers but no email is sent upon new registration.

**Comment by juan131** [comment]
Hi @yacinelazaar 

For troubleshooting SMTP issues, we have an SMTP Checker: execute these commands inside your container to download the tool:

```console
wget https://github.com/bitnami-labs/healthcheck-tools/releases/download/2.0.0/smtp-checker-v2.0.0-linux-amd64
chmod +x smtp-checker-v2.0.0-linux-amd64
```

Find out your SMTP settings and run the command:

```
./smtp-checker-v2.0.0-linux-amd64 -smtp_host YOUR_SMTP_HOST -smtp_port YOUR_SMTP_PORT -smtp_user YOUR_SMTP_USER -smtp_password YOUR_SMTP_PASS -mail_recipient YOUR_MAIL_ACCOUNT
```

> Please note that you need to replace the placeholders YOUR_SMTP_HOST, YOUR_SMTP_PORT, YOUR_SMTP_USER, YOUR_SMTP_PASS and YOUR_MAIL_ACCOUNT with the actual values you want to use.
