### ISSUE TITLE
version 1.9.5-r1 release does can't send emails to new users

### ISSUE THREAD

**Issue by rene-gomez** [bitnami/bitnami-docker-discourse#40]
**Description**

when signing a new user, the server never send any email to confirm and activate the account, the server only send test email from email settings.

**Steps to reproduce the issue:**

1. [First Step]
create a new account 
2. [Second Step]
wait a email confirmation
3. [and so on...]
the confirmation never arrives

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

- Output of `docker info`:

```
Containers: 26
 Running: 26
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 154
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-96-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 5.827GiB
Name: docker
ID: 4B6I:L3ET:6WWL:MFHG:R6Q7:O7FL:4YYV:233Y:FJQY:M3U7:UR5Y:QAZA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016

```

**Comment by juan131** [comment]
Hi @rene-gomez 

Could you share with us the `docker-compose.yaml` you're using to deploy your Discourse site? Please note that you need to indicate the env. variable associated to the SMTP configuration in order to be able to send mails. More information in the link below:

https://github.com/bitnami/bitnami-docker-discourse#smtp-configuration

**Comment by rene-gomez** [comment]
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:9.6'
    volumes:
      - 'postgresql_data:/bitnami'
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami'
  discourse:
    image: 'indiehosters/discourse'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:3000'
    depends_on:
      - postgresql
      - redis

    environment:
      - DISCOURSE_EMAIL=email@gmail.com
      - DISCOURSE_HOSTNAME=forum.domain.com
      - DISCOURSE_SITENAME=domain.com
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
       - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_DOMAIN=gmail.com
      - SMTP_USER=email@gmail.com
      - SMTP_PASSWORD=password
  sidekiq:
    image: 'bitnami/discourse:latest'
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local

**Comment by rene-gomez** [comment]
Hi @juan131 this is my actual configuration.

best regards.

**Comment by juan131** [comment]
Could you run `docker-compose exec discourse cat /opt/bitnami/discourse/config/discourse.conf`? Do you obtain sth like?

```
 smtp_address = smtp.gmail.com
    smtp_port = 587
    smtp_domain = example.com
    smtp_user_name = username@gmail.com
    smtp_password =  password
    smtp_enable_start_tls = true
    smtp_authentication = login
```

Could you try by setting `smtp_authentication = plain` (using your GMail credentials)?

**Comment by juan131** [comment]
Hi @rene-gomez  I retested-it and I was able to send mails... I think it's related to a miss-configuration on Discourse.

For troubleshooting SMTP issues, we have an SMTP Checker. Execute these commands inside your container:

```
curl -LO https://github.com/bitnami-labs/healthcheck-tools/releases/download/2.0.0/smtp-checker-v2.0.0-linux-amd64
chmod +x smtp-checker-v2.0.0-linux-amd64
```

Find out your SMTP settings and then, run the command:

```
./smtp-checker-v2.0.0-linux-amd64 -smtp_host YOUR_SMTP_HOST -smtp_port YOUR_SMTP_PORT -smtp_user YOUR_SMTP_USER -smtp_password YOUR_SMTP_PASS -mail_recipient YOUR_MAIL_ACCOUNT
```

> Please note that you need to replace the placeholders YOUR_SMTP_HOST, YOUR_SMTP_PORT, YOUR_SMTP_USER, YOUR_SMTP_PASS and YOUR_MAIL_ACCOUNT with the actual values you want to use.

Please show us the results of executing the commands.

**Comment by rene-gomez** [comment]
Hi @juan131 ths is my result:

======================================
SMTP CHECKS
======================================
Using SMTP credentials:
  - SMTP Host: "smtp.gmail.com"
  - SMTP Port: 587
  - SMTP User: "example@gmail.com"
  - SMTP Password: "password"
  - Mail Recipient: "recipient@gmail.com"

-- Check: Connectivity with SMTP server --
Succesful connectivity!
-- Check: server time offset --
Time synchronisation of host f06842a21689 within reasonable bounds!
-- Check: Send mail via SMTP --

Note: Remember to check the recipient's mail inbox!
Mail successfully sent via SMTP!

======================================
SMTP CHECKS FINISHED
======================================




but when I sign up a new ccount does not work, the email never received for the new user, if I try sign up again the system say "your username is already in use", The email is already in use", so the account work it in the server, but the serve never send the email for the firts sign up

**Comment by juan131** [comment]
> but when I sign up a new account does not work, the email never received for the new user, if I try sign up again the system say "your username is already in use", The email is already in use", so the account work it in the server, but the server never send the email for the first sign up.

Could you share with the me your configuration file? Just remove the SMTP password from the output obtained by running:

```
docker-compose exec discourse cat /bitnami/discourse/conf/discourse.conf
```

**Comment by juan131** [comment]
You can send the output to me to `juan@bitnami.com` if you don't want to share it here on GitHub

**Comment by juan131** [comment]
Hi @rene-gomez 

I was able to reproduce the issue. There must be something I'm missing since I used the same configuration file on a Bitnami Stack (Virtual Machine) and it worked perfectly but it did not work when I used it on the Docker image. 

I opened a task to investigate it more deeply. Thanks for reporting it. We will keep you updated

**Comment by Surendra-Patil** [comment]
Hi all,

Is the issue resolved ? Facing the same problem. Can sendmail be used instead of this configuration ?

**Comment by juan131** [comment]
Hi @Surendra-Patil 

This issue hasn't been resolved yet. We have at task included in our backlog but we could not work on it yet. We will update this issue once we have more news. Thanks for you consideration.



We will update this thread as soon as we have more news.

**Comment by philiprhoades** [comment]
@juan131 ,

I have the related problem and you referred me here from the Bitnami forum:

https://community.bitnami.com/t/installed-into-a-docker-container-with-smtp-host-swaks-works-discourse-doesnt/58101/2

I think I know what the problem is now - when I was testing with swaks I didn't use any auth stuff and because the Docker container was running on the host which is the Qmail server, it worked no problems - as soon as I try to do any auth with swaks, I get the same 503 error as your test script (thanks for that!).

So, I did suspect that something like this was a problem and had already deleted the fields for smtp_user and smtp_password in properties.ini but that did not help.

I think the solution is not being forced to use the smtp_user and smtp_password fields for the smtp communication - they are unnecessary in my situation - I don't have ssh access to my server from the Internet, Qmail prevents relaying from the Internet and is set up to treat my VMs and Docker containers as local.  Is there any way I can do that?

Thanks,
Phil.

**Comment by juan131** [comment]
Hi @philiprhoades 

Hi @philiprhoades 

> I don't have ssh access to my server from the Internet, Qmail prevents relaying from the Internet and is set up to treat my VMs and Docker containers as local. Is there any way I can do that?

You could create a SSH tunnel between your VM/Docker image and the server where QMail is running. Therefore, QMail will consider the connections as "local connections". Does it make sense?

**Comment by philiprhoades** [comment]
@juan131 ,

> Does it make sense? 

No . . I don't NEED SSH AT ALL - there is already NO problem with the Docker container talking to the host with Qmail - as long as the Discourse smtp communication DOESN'T use ANY auth AT ALL ie NOT use smtp_user and smtp_password . . sorry I wasn't clearer before . . ie I want TURN OFF auth - I don't need it.

**Comment by juan131** [comment]
Hi @philiprhoades 

Oh great! Sorry I misunderstood you. Apparently this topic has been deeply discussed on Discourse forums:

https://meta.discourse.org/t/cant-use-none-discourse-smtp-authentication/55833/10

Could you take a look?

**Comment by philiprhoades** [comment]
@juan131 

> Could you take a look?

That didn't help because the the app.yml file does not exist in the Bitnami stack and Discourse is not being rebuilt but it gave me the clue to eventually work out how to fix the problem - I had to add an auth line to the Bitnami properties.ini file so now my SMTP block looks like this:

[SMTP]
smtp_host=192.168.1.10
smtp_port=2525
smtp_user=
smtp_password=
smtp_protocol=none

- which works!

Thanks,
Phil.

**Comment by juan131** [comment]
Hi @philiprhoades 

Great! I'm very glad you could fix your issue adding that line. Thanks for sharing the solution.

I'll leave the issue open since the issue with the Docker image is still pending to be addressed.

**Comment by rene-gomez** [comment]
Hi @philiprhoades what is the route for this file (properties.ini), and in which container i find it?

best regards.

**Comment by dhaavi** [comment]
This is still an issue with version 2.0.2. Is there an ETA for this fix?
We'd love to use bitnami image for our instance! :)

**Comment by juan131** [comment]
We have at task included in our backlog. There are no immediate plans to work on it. Nevertheless, it will be considered for future application versions.

We will update this thread as soon as we have more news.

**Comment by rvalle** [comment]
I am facing similar problems. Email test work, yet non of the workflow emails is been sent.
I think this image is just not functional. anybody using it in production?

**Comment by Surendra-Patil** [comment]
Due to this email issue. I am using official docker image by discourse in production. No issues yet in official docker image.

**Comment by philiprhoades** [comment]
@rene-gomez 

/opt/discourse-1.9.7-0

- in the running docker container.

**Comment by rvalle** [comment]
@rene-gomez why did you not update to 2.0.3?

is it possible ot update?

**Comment by beltran-rubo** [comment]
Just a note to let you know we are actively working on fixing this issue sending emails from the application for the upcoming versions of Discourse.

**Comment by philiprhoades** [comment]
@beltran-rubo 

As I have fixed the email problem with the installed discourse-1.9.7-0 - is it possible to update Discourse in place?

**Comment by beltran-rubo** [comment]
This has been solved in the Discourse container 2.0.3-r7.

The exact issue was the Sidekiq service was only processing the jobs from the "default" queue only. If you deploy the new version, you will see in your Sidekiq page it is configured to process the jobs from all queues.

- Log in as administrator and got to "http://URL/sidekiq" -> Busy

<img width="234" alt="screen shot 2018-08-03 at 10 32 31" src="https://user-images.githubusercontent.com/3718440/43633172-b8ef24cc-9708-11e8-97b7-dc92dae2c550.png">

The exact fix for that is to replace "development" with "production" in the /opt/bitnami/discourse-sidekiq/config/sidekiq.yml file and restart the discourse-sidekiq container.

For configuring properly the SMTP properly, it is require to specify the SMTP env vars for both containers: discourse & discourse-sidekiq. Check the updated section in the README for SMTP settings.

Thanks for your feedback! @philiprhoades @rvalle @rene-gomez @dhaavi

**Comment by rene-gomez** [comment]
Hi, the problem persist, i need open a new  case for this.

@beltran-rubo my container sidekiq have the "production" but does not work

Best regards

**Comment by beltran-rubo** [comment]
yes please, open a new ticket and we can check what is the exact issue.
